[project]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "GitHub"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pre-commit = "pre-commit run --all-files"

[dependencies]
scanpy = "==1.9.5"
scikit-learn = "==1.1.3"
scvi-tools = "==1.1.1"
tqdm = ">=4.66.5,<5"
r = ">=4.3,<4.4"
r-tidyverse = ">=2.0.0,<3"
jupyterlab = ">=4.2.5,<5"
r-irkernel = ">=1.3.2,<2"
bioconductor-zellkonverter = ">=1.12.1,<2"
radian = ">=0.6.13,<0.7"
bioconductor-genomeinfodbdata = ">=1.2.11,<2"
r-biocmanager = ">=1.30.25,<2"
bioconductor-scater = ">=1.30.1,<2"
bioconductor-scran = ">=1.30.0,<2"
bioconductor-scuttle = ">=1.12.0,<2"
bioconductor-singlecellexperiment = ">=1.24.0,<2"
imageio = ">=2.35.1,<3"
alphashape = ">=1.3.1,<2"
opencv = ">=4.10.0,<5"
tifffile = ">=2024.8.28,<2025"
ipywidgets = ">=8.1.5,<9"
pre_commit = ">=3.8.0,<4"
openpyxl = ">=3.1.5,<4"
scvelo = "==0.3.1"
squidpy = ">=1.2.3,<2"
optax = "0.2.0.*"
libegl = ">=1.7.0,<2"
libopengl = ">=1.7.0,<2"
libgl = ">=1.7.0,<2"
python = ">=3.10.14,<3.11"
r-remotes = ">=2.5.0,<3"
bioconductor-complexheatmap = ">=2.18.0,<3"
r-lme4 = ">=1.1_35.5,<2"
r-future = ">=1.34.0,<2"
r-patchwork = ">=1.2.0,<2"
r-svglite = ">=2.1.3,<3"
r-rstatix = ">=0.7.2,<0.8"
r-shiny = ">=1.9.1,<2"
r-pbkrtest = ">=0.5.3,<0.6"
r-plotly = ">=4.10.4,<5"
r-ggsci = ">=3.2.0,<4"
r-ggpubr = ">=0.6.0,<0.7"
r-pbapply = ">=1.7_2,<2"
r-nmf = ">=0.21.0,<0.22"
r-ggalluvial = ">=0.12.5,<0.13"
r-network = ">=1.18.2,<2"
r-ggnetwork = ">=0.5.13,<0.6"
r-rspectra = ">=0.16_2,<0.17"
r-presto = ">=1.0.0,<2"

[pypi-dependencies]
ucell = { git = "https://github.com/maximilian-heeg/UCell.git", rev = "3d29122" }
